'use client';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { api } from '@/lib/api';
import type { WizardState } from '../hooks/useWizardState';

const LABEL_MAP: Record<string, string> = {
  EDI_204: '204 - Load Tender',
  EDI_211: '211 - BOL',
  EDI_997: '997 - Functional Acknowledgment',
  EDI_990: '990 - Response to Load Tender',
  EDI_214: '214 - Shipment Status',
  EDI_210: '210 - Freight Invoice',
};

interface Props {
  state: WizardState;
  onBack: () => void;
}

export function Step6Review({ state, onBack }: Props) {
  const [activating, setActivating] = useState(false);
  const [done, setDone] = useState(false);
  const [error, setError] = useState('');

  async function handleActivate() {
    if (!state.tradingPartnerId) {
      setError('Missing trading partner ID \u2014 please restart the wizard');
      return;
    }
    setActivating(true);
    setError('');
    try {
      await api.patchTradingPartner(state.tradingPartnerId, { isActive: true });
      setDone(true);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Activation failed');
    } finally {
      setActivating(false);
    }
  }

  if (done) {
    const partnerName = state.tradingPartnerDisplay?.name ?? 'Partner';
    return (
      <div className="max-w-lg space-y-4 text-center py-12">
        <div className="text-4xl">&#x2705;</div>
        <h3 className="text-xl font-semibold">{partnerName} is live and ready to process EDI.</h3>
        <Button onClick={() => window.location.href = '/trading-partners'}>Go to Trading Partners</Button>
      </div>
    );
  }

  const tp = state.tradingPartnerDisplay;
  const sftp = state.sftpDisplay;
  const dsApi = state.downstreamApiDisplay;

  return (
    <div className="space-y-6 max-w-lg">
      <h3 className="text-lg font-semibold">Step 6: Review &amp; Confirm</h3>

      <Section title="Trading Partner">
        <Row label="Name" value={tp?.name ?? '-'} />
        <Row label="ISA ID" value={tp?.isaId ?? '-'} />
        <Row label="GS ID" value={tp?.gsId ?? '-'} />
        <Row label="Direction" value={tp?.direction ?? '-'} />
      </Section>

      <Section title="SFTP Connection">
        <Row label="Host" value={sftp ? `${sftp.host}:${sftp.port}` : '-'} />
        <Row label="SCAC" value={sftp?.scac ?? '-'} />
        <Row label="Inbound path" value={sftp?.remotePath ?? '-'} />
        <Row label="Outbound path" value={sftp?.outboundRemotePath ?? 'Same as inbound'} />
        <Row label="Polling" value={sftp ? `${sftp.pollingIntervalSeconds}s` : '-'} />
      </Section>

      <Section title="Inbound Mappings">
        {state.inboundMappings.length === 0 ? (
          <p className="text-sm text-slate-500">Not configured</p>
        ) : (
          state.inboundMappings.map((m) => (
            <Row key={m.transactionSet} label={LABEL_MAP[m.transactionSet] ?? m.transactionSet} value={m.mappingName} />
          ))
        )}
      </Section>

      <Section title="Outbound Mappings">
        {state.outboundMappings.length === 0 && (
          <p className="text-sm text-slate-500">Not configured</p>
        )}
        {state.outboundMappings.map((m) => (
          <Row key={m.transactionSet} label={LABEL_MAP[m.transactionSet] ?? m.transactionSet} value={m.mappingName} />
        ))}
        <Row label="997 - Functional Acknowledgment" value="Auto-generated by Eddie" />
      </Section>

      <Section title="Downstream API">
        <Row label="Name" value={dsApi?.name ?? '-'} />
        <Row label="Endpoint" value={dsApi?.endpoint ?? '-'} />
        <Row label="Auth" value={dsApi?.authType ?? '-'} />
        <Row label="Timeout" value={dsApi ? `${dsApi.timeoutMs}ms` : '-'} />
      </Section>

      {error && <p className="text-sm text-red-600">{error}</p>}
      <div className="flex gap-3">
        <Button type="button" variant="outline" onClick={onBack}>Back</Button>
        <Button onClick={handleActivate} disabled={activating}>
          {activating ? 'Activating...' : 'Activate Integration'}
        </Button>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="border rounded-md p-4">
      <h4 className="font-semibold text-sm mb-2">{title}</h4>
      <div className="space-y-1">{children}</div>
    </div>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between text-sm">
      <span className="text-slate-500">{label}</span>
      <span className="font-mono text-xs">{value}</span>
    </div>
  );
}
